version: '3.9'
services:
  db:
    image: postgres:14.5-alpine
    volumes:
    - postgre_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_DB=learning
    - POSTGRES_PASSWORD=abc123.
    ports:
    - "5555:5432"
    restart: always
volumes:
  postgre_data:
    name: postgre_data
    external: false
    driver: local